### PR TITLE
new blog post

### PR DESCRIPTION
**Pull request by burnsr77**
another blog post, this time on the challenges of interdisciplinary work

### CODE REVIEW

**Comment by bernease** [comment]
Pulling the code to check the post locally.

**Comment by burnsr77** [comment]
Thanks! Might want @ShellyDianeFarnham to sign off on this one...?

**Comment by bernease** [comment]
Yes, I agree. Shelly, let me know you're okay with the content before I merge into live.

**Comment by ShellyDianeFarnham** [comment]
I like it -- though I might add "social psychologist" to the list of
disciplines in your list...e.g., when I say things like 'frequent
serendipitous interaction' is important to community development that's
straight from 30+ years of soc. science research....

I hope in doing lit reviews you guys are looking at the papers cited in the
articles I sent you; esp. the draft neighborhood study one.  I can also
point you to specific articles or books that examine communities, social
networks, esp. from a neighborhood tech perspective.

Shelly

---

Shelly D. Farnham, Ph.D.
Research Scientist / Executive Director
Third Place Technologies http://ThirdPlaceTechnologies.com
Mobile: 206-226-3586
Twitter: @ShellyShelly

**Comment by burnsr77** [comment]
Excellent! I just made the edits and submitted another pull request. Thanks!

**Pull request merged**
